apiVersion: v1
kind: Secret
metadata:
  name:  ha-lab-ipmi
stringdata:
   # Username and password for IPMI access to master and worker
   # nodes, base64-encoded
   username: root
   password: cnet
   
type: Opaque
