apiVersion: v1
baseDomain: lannion.lab
proxy:
   httpsProxy: http://10.192.64.15:8080/
   httpProxy: http://10.192.64.15:8080/
   noProxy: localhost,127.0.0.1,192.168.1.0/24,172.20.0.0/16,172.30.0.0/16,.lannion.lab
compute:
 - name: worker
   replicas: 1 
controlPlane:
   name: master
   platform: {}
   replicas: 1
metadata:
   name: okd
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
   none: {}
   apiVIP: 172.20.167.98
   ingressVIP: 172.20.167.98
   dnsVIP: 172.20.167.98
   hosts:
      # Master nodes are always RHCOS
      -  name: master-0
         role: master
         bmc:
            address: ipmi://172.20.12.170
            credentialsName: ha-lab-ipmi
         bootMACAddress: DC:F4:01:E6:0B:5D  # provisioning network mac
         sdnMacAddress: DC:F4:01:E6:0B:5C   # baremetal network mac
         # sdnIPAddress: 192.168.111.11     # Optional -- Set static IP
         hardwareProfile: default
         osProfile: 
            # With role == master, the osType is always rhcos
            # And with type rhcos, the following are settings are available
            ipxe: bios         # pxe boot type either bios (default if not specified) or uefi
                              # all masters must have the same pxe value.  Either defaulting to bios
                              # or all masters with pxe: uefi
            install_dev: sda  # where to install the operating system (sda is the default)

      # Worker nodes can be either rhcos (default) || centos (7.x) || rhel (8.x)
      -  name: worker-0
         role: worker
         bmc: 
            address: ipmi://172.20.12.171
            credentialsName: ha-lab-ipmi
         bootMACAddress: DC:F4:01:E6:0B:2D
         sdnMacAddress: DC:F4:01:E6:0B:2C
         hardwareProfile: default
         # If an osProfile/type is not defined, rhe node defaults to RHCOS
         osProfile: 
            # type: centos7
            # With type: rhcos the following are settings are available
            pxe: bios         # pxe boot type either bios (default if not specified) or uefi
            install_dev: sda  # where to install the operating system (sda is the default)

pullSecret: 'PULL_SECRET'  <- Do not change anything here as this is automatically pulled from installer node
sshKey: |
   SSH_PUB_KEY             <- Do not change anything here as this is automatically pulled from installer node
